### ISSUE TITLE
sfpassign: add note about starting from 0

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#473]
sfpassign does work but assigning presets to the numbers should start from 0, counting up.
Otherwise it reports 'invalid soundfont'

A note about this should be on the manual page

**Comment by csounder** [comment]
It would be great if the opcode itself took care of this check for the user

**Comment by jpffitch** [comment]
Can you post an exampe of it failing?  I have not seen one yet

**Comment by csounder** [comment]
Yes.  It is a bit late for you now, but I will have one for you by tomorrow.  I have been working on the Bela all day.  And... will look forward to setting you up next week and getting some advice from you about arrays.

Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music

**Comment by tjingboem** [comment]
great that this is fixed, thanks!

**Comment by jpffitch** [comment]
This issue is not fixed.  it still segfaults on destroying the module.

Still wirking on it

Example of failure is manual example sfplaym.csd and wait for the full 
minute.
